package com.example.studysmart.presentation.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF0F3C8E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFABC2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A43)
val md_theme_light_secondary = Color(0xFF3F4759)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFBCC4D6)
val md_theme_light_onSecondaryContainer = Color(0xFF141B2C)
val md_theme_light_tertiary = Color(0xFF4E3F5A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEB9FD6)
val md_theme_light_onTertiaryContainer = Color(0xFF2A132D)
val md_theme_light_error = Color(0xFF8A1414)
val md_theme_light_errorContainer = Color(0xFFFFB1AB)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFDDD7E5)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFDDD7E5)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFBCC1D0)
val md_theme_light_onSurfaceVariant = Color(0xFF44474F)
val md_theme_light_outline = Color(0xFF4E525E)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFAEC6FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0F3C8E)
val md_theme_light_outlineVariant = Color(0xFFBCC1D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF7A9AFF)
val md_theme_dark_onPrimary = Color(0xFF00316C)
val md_theme_dark_primaryContainer = Color(0xFF004B9F)
val md_theme_dark_onPrimaryContainer = Color(0xFFABC2FF)
val md_theme_dark_secondary = Color(0xFFBCC7D5)
val md_theme_dark_onSecondary = Color(0xFF293041)
val md_theme_dark_secondaryContainer = Color(0xFF4F5A6D)
val md_theme_dark_onSecondaryContainer = Color(0xFFBCC4D6)
val md_theme_dark_tertiary = Color(0xFFB882C1)
val md_theme_dark_onTertiary = Color(0xFF402843)
val md_theme_dark_tertiaryContainer = Color(0xFF5C3F6F)
val md_theme_dark_onTertiaryContainer = Color(0xFFEB9FD6)
val md_theme_dark_error = Color(0xFFFF7B73)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFB1AB)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFBDC4D2)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFBDC4D2)
val md_theme_dark_surfaceVariant = Color(0xFF44474F)
val md_theme_dark_onSurfaceVariant = Color(0xFFBCC1D0)
val md_theme_dark_outline = Color(0xFF5F6269)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFBDC4D2)
val md_theme_dark_inversePrimary = Color(0xFF0F3C8E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7A9AFF)
val md_theme_dark_outlineVariant = Color(0xFF44474F)
val md_theme_dark_scrim = Color(0xFF000000)

val Red = Color(0xFF9E2A1A)
val Blue = Color(0xFF1C4D98)
val Green = Color(0xFF176D3E)
val Orange = Color(0xFFFB8A00)

val gradient1 = listOf(Color(0xFF8A3D6E), Color(0xFF5B1539))
val gradient2 = listOf(Color(0xFF2D4B5D), Color(0xFF0F1415))
val gradient3 = listOf(Color(0xFFED3296), Color(0xFFEF1F1F))
val gradient4 = listOf(Color(0xFF00A1CC), Color(0xFF265993))
val gradient5 = listOf(Color(0xFF70D8A3), Color(0xFF0D2D28))
